import type { Attachment } from "@/lib/types";

export const attachmentsMaria: Attachment[] = [
  {
    id: "att-mk-001",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "pdf",
    name: "Core biopsy report — left breast",
    date: "2026-02-08T09:14:00Z",
    source: "Path-Lab Vienna",
    sizeKb: 412,
    pages: 4,
  },
  {
    id: "att-mk-002",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "image",
    name: "IHC HER2 — 3+ membrane stain",
    date: "2026-02-09T15:02:00Z",
    source: "Path-Lab Vienna",
    sizeKb: 1820,
    gradient: "from-rose-300 via-pink-200 to-amber-200",
  },
  {
    id: "att-mk-003",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "image",
    name: "Mammogram — bilateral",
    date: "2026-02-04T10:30:00Z",
    source: "Radiology Dept.",
    sizeKb: 2840,
    gradient: "from-slate-700 via-slate-500 to-slate-300",
  },
  {
    id: "att-mk-004",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "image",
    name: "MRI breast — pre-treatment",
    date: "2026-02-12T11:45:00Z",
    source: "Radiology Dept.",
    sizeKb: 5120,
    gradient: "from-slate-900 via-indigo-700 to-violet-500",
  },
  {
    id: "att-mk-005",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "pdf",
    name: "Restaging MRI report",
    date: "2026-04-22T14:08:00Z",
    source: "Radiology Dept.",
    sizeKb: 376,
    pages: 3,
  },
  {
    id: "att-mk-006",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "table",
    name: "CBC trend — 6 cycles",
    date: "2026-04-18T08:00:00Z",
    source: "EHR / labs",
    rows: 6,
    cols: 5,
  },
  {
    id: "att-mk-007",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "report",
    name: "Cycle 4 visit note",
    date: "2026-04-15T10:30:00Z",
    source: "Dr. J. Müller",
    excerpt:
      "Tolerating TCHP cycle 4 well. ECOG 1. Mild peripheral neuropathy grade 1. LVEF 62%, stable.",
  },
  {
    id: "att-mk-008",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "pdf",
    name: "NGS panel — 523 genes",
    date: "2026-02-18T16:20:00Z",
    source: "Molecular Path",
    sizeKb: 198,
    pages: 12,
  },
  {
    id: "att-mk-009",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "report",
    name: "Pre-op surgical consult",
    date: "2026-04-20T11:00:00Z",
    source: "Dr. R. Pavlik",
    excerpt:
      "Candidate for breast-conserving therapy pending response on restaging MRI. Sentinel node mapping planned.",
  },
  {
    id: "att-mk-010",
    patientId: "maria-k",
    specialty: "nursing",
    kind: "table",
    name: "Infusion log — TCHP",
    date: "2026-04-15T09:00:00Z",
    source: "Infusion clinic",
    rows: 4,
    cols: 4,
  },
  {
    id: "att-mk-011",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "pdf",
    name: "Baseline assessment — Dr. Muller",
    date: "2026-02-10T11:00:00Z",
    source: "Dr. J. Müller",
    sizeKb: 220,
    pages: 3,
  },
  {
    id: "att-mk-012",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "pdf",
    name: "Staging CT chest/abdomen/pelvis report",
    date: "2026-02-18T10:30:00Z",
    source: "Dr. K. Lee, Radiology",
    sizeKb: 310,
    pages: 2,
  },
  {
    id: "att-mk-013",
    patientId: "maria-k",
    specialty: "nursing",
    kind: "report",
    name: "Intake form",
    date: "2026-02-08T09:12:00Z",
    source: "Reception",
    excerpt: "Patient: Maria Kowalski, DOB 1971-09-14, female. NKDA.",
  },
];

export const attachmentsThomas: Attachment[] = [
  {
    id: "att-tb-001",
    patientId: "thomas-b",
    specialty: "pathology",
    kind: "pdf",
    name: "Colonoscopy biopsy — adenocarcinoma",
    date: "2026-03-04T15:20:00Z",
    source: "Dr. M. Schwarz, GI Path",
    sizeKb: 380,
    pages: 5,
  },
  {
    id: "att-tb-002",
    patientId: "thomas-b",
    specialty: "pathology",
    kind: "pdf",
    name: "MSI/IHC panel report",
    date: "2026-03-06T10:00:00Z",
    source: "Dr. M. Schwarz, GI Path",
    sizeKb: 165,
    pages: 2,
  },
  {
    id: "att-tb-003",
    patientId: "thomas-b",
    specialty: "pathology",
    kind: "pdf",
    name: "Molecular panel — KRAS/NRAS/BRAF",
    date: "2026-03-10T14:00:00Z",
    source: "Dr. M. Schwarz, GI Path",
    sizeKb: 210,
    pages: 6,
  },
  {
    id: "att-tb-004",
    patientId: "thomas-b",
    specialty: "radiology",
    kind: "pdf",
    name: "Staging CT chest/abdomen/pelvis",
    date: "2026-03-06T09:00:00Z",
    source: "Dr. K. Lee, Radiology",
    sizeKb: 295,
    pages: 3,
  },
  {
    id: "att-tb-005",
    patientId: "thomas-b",
    specialty: "radiology",
    kind: "image",
    name: "Pelvic MRI — baseline",
    date: "2026-03-08T11:10:00Z",
    source: "Dr. K. Lee, Radiology",
    sizeKb: 6200,
    gradient: "from-slate-800 via-slate-600 to-slate-400",
  },
  {
    id: "att-tb-006",
    patientId: "thomas-b",
    specialty: "radiology",
    kind: "pdf",
    name: "Pelvic MRI report — EMVI/distance",
    date: "2026-03-08T11:10:00Z",
    source: "Dr. K. Lee, Radiology",
    sizeKb: 175,
    pages: 2,
  },
  {
    id: "att-tb-007",
    patientId: "thomas-b",
    specialty: "med-onc",
    kind: "pdf",
    name: "Baseline assessment — Dr. Romano",
    date: "2026-03-02T10:00:00Z",
    source: "Dr. C. Romano, Med-Onc",
    sizeKb: 240,
    pages: 4,
  },
  {
    id: "att-tb-008",
    patientId: "thomas-b",
    specialty: "med-onc",
    kind: "table",
    name: "CEA trend — pre/post induction",
    date: "2026-04-20T08:00:00Z",
    source: "Biochemistry lab",
    rows: 3,
    cols: 4,
  },
  {
    id: "att-tb-009",
    patientId: "thomas-b",
    specialty: "med-onc",
    kind: "table",
    name: "CMP — liver/renal function",
    date: "2026-03-14T08:00:00Z",
    source: "Biochemistry lab",
    rows: 8,
    cols: 3,
  },
  {
    id: "att-tb-010",
    patientId: "thomas-b",
    specialty: "med-onc",
    kind: "report",
    name: "Toxicity assessment — neuropathy",
    date: "2026-04-10T11:00:00Z",
    source: "Dr. C. Romano, Med-Onc",
    excerpt: "Grade 1 cold-triggered paresthesias, onset cycle 3. No functional impairment.",
  },
  {
    id: "att-tb-011",
    patientId: "thomas-b",
    specialty: "med-onc",
    kind: "report",
    name: "Post-induction response assessment",
    date: "2026-04-22T17:00:00Z",
    source: "Dr. C. Romano, Med-Onc",
    excerpt: "CEA halved (8.4→4.2). Restaging MRI shows ~30% reduction. Partial response.",
  },
  {
    id: "att-tb-012",
    patientId: "thomas-b",
    specialty: "nursing",
    kind: "report",
    name: "Intake form",
    date: "2026-03-01T08:30:00Z",
    source: "Reception",
    excerpt: "Patient: Thomas Berger, DOB 1958-11-22, male. Retired engineer. NKDA.",
  },
  {
    id: "att-tb-013",
    patientId: "thomas-b",
    specialty: "nursing",
    kind: "report",
    name: "Infusion note — cycle 4",
    date: "2026-04-18T14:20:00Z",
    source: "Onc nursing",
    excerpt: "No infusion reactions. Full doses delivered all cycles. Grade 1 nausea managed.",
  },
  {
    id: "att-tb-014",
    patientId: "thomas-b",
    specialty: "nursing",
    kind: "table",
    name: "Infusion log — FOLFOX 4 cycles",
    date: "2026-04-18T14:20:00Z",
    source: "Infusion clinic",
    rows: 4,
    cols: 4,
  },
];

export const attachmentsAnna: Attachment[] = [
  {
    id: "att-al-001",
    patientId: "anna-l",
    specialty: "pathology",
    kind: "pdf",
    name: "Lumpectomy specimen — surgical path",
    date: "2024-04-12T11:00:00Z",
    source: "Dr. R. Patel, MD",
    sizeKb: 450,
    pages: 6,
  },
  {
    id: "att-al-002",
    patientId: "anna-l",
    specialty: "pathology",
    kind: "pdf",
    name: "Ki-67 addendum",
    date: "2024-04-14T09:00:00Z",
    source: "Dr. R. Patel, MD",
    sizeKb: 78,
    pages: 1,
  },
  {
    id: "att-al-003",
    patientId: "anna-l",
    specialty: "pathology",
    kind: "pdf",
    name: "Oncotype DX recurrence score report",
    date: "2024-05-02T10:00:00Z",
    source: "Genomic Health",
    sizeKb: 340,
    pages: 8,
  },
  {
    id: "att-al-004",
    patientId: "anna-l",
    specialty: "pathology",
    kind: "pdf",
    name: "Germline panel — BRCA1/2, PALB2, CHEK2",
    date: "2024-05-20T14:00:00Z",
    source: "Invitae Genetics",
    sizeKb: 195,
    pages: 4,
  },
  {
    id: "att-al-005",
    patientId: "anna-l",
    specialty: "radiology",
    kind: "image",
    name: "Post-surgical mammogram — bilateral",
    date: "2024-10-15T09:30:00Z",
    source: "Radiology Dept.",
    sizeKb: 3100,
    gradient: "from-slate-700 via-slate-500 to-slate-300",
  },
  {
    id: "att-al-006",
    patientId: "anna-l",
    specialty: "radiology",
    kind: "pdf",
    name: "Post-surgical mammogram report",
    date: "2024-10-15T09:30:00Z",
    source: "Radiology Dept.",
    sizeKb: 130,
    pages: 2,
  },
  {
    id: "att-al-007",
    patientId: "anna-l",
    specialty: "radiology",
    kind: "pdf",
    name: "DEXA scan — bone density baseline",
    date: "2024-06-10T10:00:00Z",
    source: "Radiology Dept.",
    sizeKb: 95,
    pages: 2,
  },
  {
    id: "att-al-008",
    patientId: "anna-l",
    specialty: "med-onc",
    kind: "report",
    name: "Tamoxifen adherence review",
    date: "2025-04-01T14:00:00Z",
    source: "Dr. L. Fischer, Med-Onc",
    excerpt: "Adherent to 20mg daily tamoxifen. No dose modifications. Mild hot flashes managed.",
  },
  {
    id: "att-al-009",
    patientId: "anna-l",
    specialty: "med-onc",
    kind: "table",
    name: "Lipid panel trend",
    date: "2025-10-05T08:00:00Z",
    source: "Biochemistry lab",
    rows: 4,
    cols: 5,
  },
  {
    id: "att-al-010",
    patientId: "anna-l",
    specialty: "med-onc",
    kind: "report",
    name: "Endocrine side effects note",
    date: "2025-10-15T09:00:00Z",
    source: "Dr. L. Fischer, Med-Onc",
    excerpt: "Mild hot flashes, mild arthralgia. Weight stable. No indication to switch therapy.",
  },
  {
    id: "att-al-011",
    patientId: "anna-l",
    specialty: "nursing",
    kind: "report",
    name: "Intake form",
    date: "2024-04-01T08:00:00Z",
    source: "Reception",
    excerpt: "Patient: Anna Lindqvist, DOB 1968-03-21, female. NKDA.",
  },
  {
    id: "att-al-012",
    patientId: "anna-l",
    specialty: "nursing",
    kind: "report",
    name: "QOL assessment — FACT-B",
    date: "2025-10-15T10:00:00Z",
    source: "Nursing team",
    excerpt: "Overall QOL: 7/10. Physical well-being: 8/10. Emotional: 6/10. Sleep disruption reported.",
  },
  {
    id: "att-al-013",
    patientId: "anna-l",
    specialty: "nursing",
    kind: "report",
    name: "Contact preferences form",
    date: "2024-04-01T08:15:00Z",
    source: "Reception",
    excerpt: "Preferred contact: email. Portal access: active. Emergency contact: partner.",
  },
];
