import type { Attachment } from "@/lib/types";

export const attachmentsMaria: Attachment[] = [
  {
    id: "att-mk-001",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "pdf",
    name: "Core biopsy report — left breast",
    date: "2026-02-08T09:14:00Z",
    source: "Path-Lab Vienna",
    sizeKb: 412,
    pages: 4,
  },
  {
    id: "att-mk-002",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "image",
    name: "IHC HER2 — 3+ membrane stain",
    date: "2026-02-09T15:02:00Z",
    source: "Path-Lab Vienna",
    sizeKb: 1820,
    gradient: "from-rose-300 via-pink-200 to-amber-200",
  },
  {
    id: "att-mk-003",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "image",
    name: "Mammogram — bilateral",
    date: "2026-02-04T10:30:00Z",
    source: "Radiology Dept.",
    sizeKb: 2840,
    gradient: "from-slate-700 via-slate-500 to-slate-300",
  },
  {
    id: "att-mk-004",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "image",
    name: "MRI breast — pre-treatment",
    date: "2026-02-12T11:45:00Z",
    source: "Radiology Dept.",
    sizeKb: 5120,
    gradient: "from-slate-900 via-indigo-700 to-violet-500",
  },
  {
    id: "att-mk-005",
    patientId: "maria-k",
    specialty: "radiology",
    kind: "pdf",
    name: "Restaging MRI report",
    date: "2026-04-22T14:08:00Z",
    source: "Radiology Dept.",
    sizeKb: 376,
    pages: 3,
  },
  {
    id: "att-mk-006",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "table",
    name: "CBC trend — 6 cycles",
    date: "2026-04-18T08:00:00Z",
    source: "EHR / labs",
    rows: 6,
    cols: 5,
  },
  {
    id: "att-mk-007",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "report",
    name: "Cycle 4 visit note",
    date: "2026-04-15T10:30:00Z",
    source: "Dr. J. Müller",
    excerpt:
      "Tolerating TCHP cycle 4 well. ECOG 1. Mild peripheral neuropathy grade 1. LVEF 62%, stable.",
  },
  {
    id: "att-mk-008",
    patientId: "maria-k",
    specialty: "pathology",
    kind: "pdf",
    name: "NGS panel — 523 genes",
    date: "2026-02-18T16:20:00Z",
    source: "Molecular Path",
    sizeKb: 198,
    pages: 12,
  },
  {
    id: "att-mk-009",
    patientId: "maria-k",
    specialty: "med-onc",
    kind: "report",
    name: "Pre-op surgical consult",
    date: "2026-04-20T11:00:00Z",
    source: "Dr. R. Pavlik",
    excerpt:
      "Candidate for breast-conserving therapy pending response on restaging MRI. Sentinel node mapping planned.",
  },
  {
    id: "att-mk-010",
    patientId: "maria-k",
    specialty: "nursing",
    kind: "table",
    name: "Infusion log — TCHP",
    date: "2026-04-15T09:00:00Z",
    source: "Infusion clinic",
    rows: 4,
    cols: 4,
  },
];
