import type { Fact, Patient } from "../types";

const factsMaria: Fact[] = [
  {
    id: "f-mk-name",
    key: "demographics.name",
    label: "Name",
    value: "Maria Kowalski",
    confidence: 1,
    group: "demographics",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "Intake form · 2026-02-08",
      excerpt: "Patient: Maria Kowalski, DOB 1971-09-14, female",
      at: "2026-02-08T09:12:00Z",
      author: "Reception",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1971-09-14",
    confidence: 1,
    group: "demographics",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "Intake form · 2026-02-08",
      at: "2026-02-08T09:12:00Z",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-204881",
    confidence: 1,
    group: "demographics",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "EHR registration",
      at: "2026-02-08T09:12:00Z",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Invasive ductal carcinoma, left breast",
    confidence: 0.99,
    group: "diagnosis",
    source: {
      kind: "pathology",
      id: "path-mk-001",
      label: "Path report · core biopsy 2026-02-12",
      excerpt:
        "Microscopic: invasive ductal carcinoma, Nottingham grade 2 (3+3+1=7). Tumor measures 2.3 cm in greatest dimension on the core.",
      author: "Dr. R. Patel, MD",
      at: "2026-02-13T14:30:00Z",
    },
    updatedAt: "2026-02-13T14:30:00Z",
  },
  {
    id: "f-mk-receptors",
    key: "diagnosis.receptors",
    label: "Receptor status",
    value: "ER+ (95%) · PR+ (60%) · HER2 3+ (IHC) confirmed by FISH",
    confidence: 0.98,
    group: "diagnosis",
    source: {
      kind: "pathology",
      id: "path-mk-002",
      label: "IHC + FISH addendum · 2026-02-15",
      excerpt:
        "ER 95% strong, PR 60% moderate, HER2 IHC 3+; FISH HER2/CEP17 ratio 4.2 — amplified.",
      author: "Dr. R. Patel, MD",
      at: "2026-02-15T11:05:00Z",
    },
    updatedAt: "2026-02-15T11:05:00Z",
  },
  {
    id: "f-mk-stage",
    key: "staging.clinical",
    label: "Clinical stage",
    value: "cT2 cN1 cM0 — Stage IIB",
    confidence: 0.95,
    group: "staging",
    source: {
      kind: "imaging",
      id: "img-mk-mri-001",
      label: "Breast MRI · 2026-02-19",
      excerpt:
        "2.4 cm enhancing mass at 2 o'clock left breast; one suspicious left axillary level I node (1.1 cm).",
      author: "Dr. K. Lee, Radiology",
      at: "2026-02-19T16:40:00Z",
    },
    updatedAt: "2026-02-19T16:40:00Z",
  },
  {
    id: "f-mk-tchp",
    key: "medication.neoadjuvant",
    label: "Neoadjuvant regimen",
    value: "TCHP — docetaxel + carboplatin + trastuzumab + pertuzumab, q3w × 6",
    confidence: 0.97,
    group: "medication",
    source: {
      kind: "note",
      id: "note-mk-tb-1",
      label: "Tumor board minutes · 2026-02-22",
      excerpt:
        "Consensus: HER2+ Stage IIB → neoadjuvant TCHP × 6 → surgery → adjuvant HP + endocrine therapy.",
      author: "Tumor board",
      at: "2026-02-22T10:00:00Z",
    },
    updatedAt: "2026-02-22T10:00:00Z",
  },
  {
    id: "f-mk-cycle",
    key: "medication.cycle",
    label: "Current cycle",
    value: "TCHP cycle 4 of 6 — last infusion 2026-04-15",
    confidence: 1,
    group: "medication",
    source: {
      kind: "note",
      id: "note-mk-infusion-4",
      label: "Infusion note · 2026-04-15",
      author: "Onc nursing",
      at: "2026-04-15T13:00:00Z",
    },
    updatedAt: "2026-04-15T13:00:00Z",
  },
  {
    id: "f-mk-lvef",
    key: "lab.lvef",
    label: "LVEF (echo)",
    value: "62% — within normal limits",
    confidence: 0.99,
    group: "lab",
    source: {
      kind: "report",
      id: "echo-mk-002",
      label: "Echocardiogram · 2026-04-22",
      excerpt:
        "Normal LV size and systolic function. EF 62% by Simpson biplane. No regional wall abnormalities.",
      author: "Dr. A. Singh, Cardiology",
      at: "2026-04-22T09:30:00Z",
    },
    updatedAt: "2026-04-22T09:30:00Z",
  },
  {
    id: "f-mk-cbc",
    key: "lab.cbc",
    label: "ANC (latest)",
    value: "2.1 ×10⁹/L",
    confidence: 1,
    group: "lab",
    source: {
      kind: "lab",
      id: "lab-mk-cbc-3",
      label: "CBC · 2026-04-21",
      author: "Hematology lab",
      at: "2026-04-21T08:15:00Z",
    },
    updatedAt: "2026-04-21T08:15:00Z",
  },
  {
    id: "f-mk-hist1",
    key: "history.event.first-presentation",
    label: "First presentation",
    value: "Self-detected 2 cm lump, left breast — 2026-02-04",
    confidence: 0.95,
    group: "history",
    source: {
      kind: "note",
      id: "note-mk-pcp",
      label: "PCP referral letter",
      at: "2026-02-06T10:00:00Z",
    },
    updatedAt: "2026-02-06T10:00:00Z",
  },
];

const factsThomas: Fact[] = [
  {
    id: "f-tb-name",
    key: "demographics.name",
    label: "Name",
    value: "Thomas Berger",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-tb-intake", label: "Intake form · 2026-03-01", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1958-06-21",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-tb-intake", label: "Intake form", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-198342",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-tb-intake", label: "EHR registration", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Adenocarcinoma of the rectum, mid-rectum (8 cm from anal verge)",
    confidence: 0.99,
    group: "diagnosis",
    source: {
      kind: "pathology",
      id: "path-tb-001",
      label: "Colonoscopy biopsy report · 2026-03-04",
      excerpt:
        "Mid-rectum 3.5 cm ulcerated mass at 8 cm from anal verge. Biopsy: moderately differentiated adenocarcinoma.",
      author: "Dr. M. Schwarz, GI Path",
      at: "2026-03-04T15:20:00Z",
    },
    updatedAt: "2026-03-04T15:20:00Z",
  },
  {
    id: "f-tb-stage",
    key: "staging.clinical",
    label: "Clinical stage",
    value: "cT3 cN1 cM0 — Stage IIIB",
    confidence: 0.7,
    group: "staging",
    source: {
      kind: "imaging",
      id: "img-tb-mri-001",
      label: "Pelvic MRI · 2026-03-08",
      excerpt:
        "Mid-rectal mass with extramural extension into mesorectal fat (cT3, EMVI−). One suspicious mesorectal node 9 mm.",
      author: "Dr. K. Lee, Radiology",
      at: "2026-03-08T11:10:00Z",
    },
    updatedAt: "2026-03-08T11:10:00Z",
  },
  {
    id: "f-tb-cea",
    key: "lab.cea",
    label: "CEA",
    value: "8.4 ng/mL (elevated)",
    confidence: 1,
    group: "lab",
    source: { kind: "lab", id: "lab-tb-cea-1", label: "CEA · 2026-03-05", at: "2026-03-05T07:50:00Z" },
    updatedAt: "2026-03-05T07:50:00Z",
  },
  {
    id: "f-tb-folfox",
    key: "medication.induction",
    label: "Induction chemotherapy",
    value: "FOLFOX × 4 cycles (TNT — induction phase)",
    confidence: 0.96,
    group: "medication",
    source: {
      kind: "note",
      id: "note-tb-tb-1",
      label: "Tumor board minutes · 2026-03-12",
      excerpt:
        "Plan: total neoadjuvant therapy — induction FOLFOX × 4 → long-course CRT → TME → adjuvant if indicated.",
      author: "Tumor board",
      at: "2026-03-12T09:00:00Z",
    },
    updatedAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "f-tb-cycle",
    key: "medication.cycle",
    label: "Current cycle",
    value: "FOLFOX cycle 4 of 4 — completed 2026-04-18",
    confidence: 1,
    group: "medication",
    source: {
      kind: "note",
      id: "note-tb-infusion-4",
      label: "Infusion note · 2026-04-18",
      at: "2026-04-18T14:20:00Z",
    },
    updatedAt: "2026-04-18T14:20:00Z",
  },
  {
    id: "f-tb-mri-restage",
    key: "imaging.restage",
    label: "Restaging MRI",
    value: "Pelvic MRI · 2026-04-22 (incoming PR)",
    confidence: 0.85,
    group: "imaging",
    source: {
      kind: "imaging",
      id: "img-tb-mri-002",
      label: "Pelvic MRI · 2026-04-22",
      excerpt:
        "Compared to 2026-03-08: tumor enhancement reduced ~30% but anterior extension now contacts visceral peritoneum (suggestive of cT4a). One persistent 7 mm mesorectal node.",
      author: "Dr. K. Lee, Radiology",
      at: "2026-04-22T16:00:00Z",
    },
    updatedAt: "2026-04-22T16:00:00Z",
  },
];

const factsAnna: Fact[] = [
  {
    id: "f-al-name",
    key: "demographics.name",
    label: "Name",
    value: "Anna Lindqvist",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-al-intake", label: "Intake form · 2024-02-19", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1977-11-02",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-al-intake", label: "Intake form", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-176104",
    confidence: 1,
    group: "demographics",
    source: { kind: "report", id: "doc-al-intake", label: "EHR registration", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Invasive lobular carcinoma, right breast",
    confidence: 0.98,
    group: "diagnosis",
    source: {
      kind: "pathology",
      id: "path-al-001",
      label: "Lumpectomy specimen · 2024-04-09",
      excerpt:
        "Invasive lobular carcinoma, 1.4 cm, grade 2. Margins clear. 0/2 sentinel nodes positive.",
      author: "Dr. R. Patel, MD",
      at: "2024-04-12T11:00:00Z",
    },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-stage",
    key: "staging.pathologic",
    label: "Pathologic stage",
    value: "pT1c pN0 — Stage IA",
    confidence: 0.99,
    group: "staging",
    source: {
      kind: "pathology",
      id: "path-al-001",
      label: "Lumpectomy specimen · 2024-04-09",
      at: "2024-04-12T11:00:00Z",
    },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-receptors",
    key: "diagnosis.receptors",
    label: "Receptor status",
    value: "ER+ (98%) · PR+ (75%) · HER2 0 (negative)",
    confidence: 0.98,
    group: "diagnosis",
    source: { kind: "pathology", id: "path-al-001", label: "IHC panel", at: "2024-04-12T11:00:00Z" },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-tam",
    key: "medication.endocrine",
    label: "Endocrine therapy",
    value: "Tamoxifen 20 mg daily — start 2024-08-12, planned ≥ 5 yrs",
    confidence: 1,
    group: "medication",
    source: {
      kind: "note",
      id: "note-al-tam",
      label: "Med-onc note · 2024-08-05",
      author: "Dr. J. Müller, Med-Onc",
      at: "2024-08-05T13:00:00Z",
    },
    updatedAt: "2024-08-05T13:00:00Z",
  },
  {
    id: "f-al-mam",
    key: "imaging.surveillance",
    label: "Last mammogram",
    value: "Bilateral mammogram · 2025-10-14 — BI-RADS 2 (benign)",
    confidence: 0.99,
    group: "imaging",
    source: {
      kind: "imaging",
      id: "img-al-mam-3",
      label: "Mammogram · 2025-10-14",
      author: "Dr. K. Lee, Radiology",
      at: "2025-10-14T09:00:00Z",
    },
    updatedAt: "2025-10-14T09:00:00Z",
  },
  {
    id: "f-al-ca153",
    key: "lab.ca153",
    label: "CA 15-3",
    value: "21 U/mL (within normal)",
    confidence: 1,
    group: "lab",
    source: { kind: "lab", id: "lab-al-ca153-2", label: "CA 15-3 · 2026-04-04", at: "2026-04-04T08:00:00Z" },
    updatedAt: "2026-04-04T08:00:00Z",
  },
];

export const patients: Patient[] = [
  {
    id: "maria-k",
    name: "Maria Kowalski",
    initials: "MK",
    dob: "1971-09-14",
    age: 54,
    sex: "F",
    mrn: "MRN-204881",
    status: "active",
    cancerType: "breast-her2",
    cancerLabel: "HER2+ breast cancer · Stage IIB",
    diagnosis: "Invasive ductal carcinoma, ER+/PR+/HER2 3+",
    staging: "cT2 cN1 cM0",
    primaryOncologist: "Dr. J. Müller, Med-Onc",
    caseOpenedAt: "2026-02-08",
    avatarTone: "rose",
    vaultAvatars: [
      { initials: "JM", tone: "violet" },
      { initials: "RP", tone: "rose" },
      { initials: "AS", tone: "emerald" },
      { initials: "KL", tone: "amber" },
    ],
    facts: factsMaria,
    plan: [
      {
        id: "ph-mk-1",
        name: "Neoadjuvant TCHP",
        type: "chemo",
        regimen: "Docetaxel · carboplatin · trastuzumab · pertuzumab",
        status: "in-progress",
        startDate: "2026-02-25",
        endDate: "2026-06-10",
        cycles: { total: 6, completed: 4 },
        rationale: "HER2+ Stage IIB → standard of care neoadjuvant TCHP × 6 (NCCN BINV-J).",
      },
      {
        id: "ph-mk-2",
        name: "Surgery",
        type: "surgery",
        regimen: "Lumpectomy + sentinel node biopsy (axillary dissection if positive)",
        status: "planned",
        startDate: "2026-07-08",
        rationale: "Clinical stage IIB with planned breast-conserving therapy if good response.",
      },
      {
        id: "ph-mk-3",
        name: "Adjuvant HP",
        type: "targeted",
        regimen: "Trastuzumab + pertuzumab to complete 1 year HER2-targeted therapy",
        status: "planned",
        startDate: "2026-08-12",
        endDate: "2027-02-25",
        rationale: "1-year HER2 blockade reduces recurrence risk.",
      },
      {
        id: "ph-mk-4",
        name: "Adjuvant endocrine",
        type: "hormonal",
        regimen: "Aromatase inhibitor (post-menopausal) for ≥ 5 years",
        status: "planned",
        startDate: "2026-08-12",
        rationale: "ER/PR positive disease — endocrine therapy for ≥ 5 years.",
      },
    ],
    agent: {
      now: {
        action: "Reviewing 2026-04-22 echocardiogram for trastuzumab cardiac monitoring",
      },
      needsYou: [
        {
          id: "q-mk-1",
          question: "Confirm continued TCHP after Cycle 4 — ANC 2.1, no DLT",
          detail:
            "Neutrophils marginal but acceptable per protocol. Endorse continuation of cycle 5 on schedule?",
          ref: { kind: "fact", id: "f-mk-cbc", label: "ANC 2.1 ×10⁹/L" },
          options: ["Continue on schedule", "Delay 1 week", "Reduce dose"],
        },
      ],
      recent: [
        {
          id: "ev-mk-1",
          action: "Merged echocardiogram report · LVEF 62%",
          at: "2026-04-22T11:02:00Z",
          ref: { kind: "pr", id: "pr-mk-2", label: "Echo 2026-04-22" },
        },
        {
          id: "ev-mk-2",
          action: "Linked CBC 2026-04-21 to cycle 4 progress",
          at: "2026-04-21T08:30:00Z",
        },
        {
          id: "ev-mk-3",
          action: "Auto-scheduled mid-treatment MRI for 2026-05-13",
          at: "2026-04-19T16:14:00Z",
        },
      ],
    },
  },
  {
    id: "thomas-b",
    name: "Thomas Berger",
    initials: "TB",
    dob: "1958-06-21",
    age: 67,
    sex: "M",
    mrn: "MRN-198342",
    status: "active",
    cancerType: "rectal",
    cancerLabel: "Rectal adenocarcinoma · TNT in progress",
    diagnosis: "Adenocarcinoma of the rectum, mid-rectum",
    staging: "cT3 cN1 cM0 (provisional → cT4a pending)",
    primaryOncologist: "Dr. C. Romano, Med-Onc",
    caseOpenedAt: "2026-03-01",
    avatarTone: "violet",
    vaultAvatars: [
      { initials: "CR", tone: "violet" },
      { initials: "MS", tone: "rose" },
      { initials: "KL", tone: "amber" },
      { initials: "FP", tone: "sky" },
    ],
    facts: factsThomas,
    plan: [
      {
        id: "ph-tb-1",
        name: "Induction FOLFOX",
        type: "chemo",
        regimen: "Oxaliplatin + 5-FU + leucovorin, q2w × 4",
        status: "done",
        startDate: "2026-03-15",
        endDate: "2026-04-18",
        cycles: { total: 4, completed: 4 },
        rationale: "Total neoadjuvant therapy — induction phase.",
      },
      {
        id: "ph-tb-2",
        name: "Long-course CRT",
        type: "radiation",
        regimen: "50.4 Gy in 28 fractions + concurrent capecitabine",
        status: "planned",
        startDate: "2026-05-06",
        endDate: "2026-06-17",
        rationale: "TNT consolidation — long-course chemoradiation.",
      },
      {
        id: "ph-tb-3",
        name: "TME surgery",
        type: "surgery",
        regimen: "Total mesorectal excision (low anterior resection)",
        status: "planned",
        startDate: "2026-08-05",
        rationale:
          "Standard surgical approach following TNT, 6–8 weeks after CRT completion.",
      },
      {
        id: "ph-tb-4",
        name: "Adjuvant (if indicated)",
        type: "chemo",
        regimen: "Adjuvant FOLFOX or capecitabine if path response < grade 3",
        status: "planned",
        startDate: "2026-09-23",
        rationale: "Risk-adapted adjuvant per pathologic response.",
      },
    ],
    agent: {
      now: {
        action: "Reconciling restaging MRI vs. baseline staging",
        ref: { kind: "pr", id: "pr-tb-1", label: "PR #3 — MRI 2026-04-22" },
      },
      needsYou: [
        {
          id: "q-tb-1",
          question: "MRI 2026-04-22 suggests cT4a — change of staging vs. cT3",
          detail:
            "Anterior extension contacts visceral peritoneum. This conflicts with the prior cT3 from 2026-03-08. Possible explanations: progression on induction, MRI re-read, or interval inflammation. Plan implications: TNT may need to escalate, consider surgical re-staging.",
          ref: { kind: "pr", id: "pr-tb-1", label: "PR #3 — MRI 2026-04-22" },
          options: [
            "Accept cT4a — escalate plan",
            "Request second MRI read",
            "Discuss at tumor board",
          ],
        },
      ],
      recent: [
        {
          id: "ev-tb-1",
          action: "Flagged staging conflict on MRI 2026-04-22",
          at: "2026-04-22T17:14:00Z",
          ref: { kind: "pr", id: "pr-tb-1", label: "PR #3" },
        },
        {
          id: "ev-tb-2",
          action: "Merged FOLFOX cycle 4 infusion note",
          at: "2026-04-18T15:00:00Z",
        },
        {
          id: "ev-tb-3",
          action: "Auto-booked tumor board slot · 2026-04-26 09:00",
          at: "2026-04-22T17:30:00Z",
          ref: { kind: "meeting", id: "mtg-tb-1", label: "Tumor board · 2026-04-26" },
        },
      ],
    },
  },
  {
    id: "anna-l",
    name: "Anna Lindqvist",
    initials: "AL",
    dob: "1977-11-02",
    age: 48,
    sex: "F",
    mrn: "MRN-176104",
    status: "surveillance",
    cancerType: "breast-er",
    cancerLabel: "ER+ breast cancer · Surveillance · 23 mo",
    diagnosis: "Invasive lobular carcinoma, ER+/PR+/HER2−",
    staging: "pT1c pN0 — Stage IA",
    primaryOncologist: "Dr. J. Müller, Med-Onc",
    caseOpenedAt: "2024-02-19",
    avatarTone: "emerald",
    vaultAvatars: [
      { initials: "JM", tone: "violet" },
      { initials: "RP", tone: "rose" },
      { initials: "KL", tone: "amber" },
    ],
    facts: factsAnna,
    plan: [
      {
        id: "ph-al-1",
        name: "Lumpectomy + SLNB",
        type: "surgery",
        status: "done",
        startDate: "2024-04-09",
        endDate: "2024-04-09",
        rationale: "Breast-conserving surgery, sentinel node biopsy negative.",
      },
      {
        id: "ph-al-2",
        name: "Adjuvant radiation",
        type: "radiation",
        regimen: "Whole-breast 40.05 Gy in 15 fractions",
        status: "done",
        startDate: "2024-06-03",
        endDate: "2024-07-12",
      },
      {
        id: "ph-al-3",
        name: "Endocrine therapy",
        type: "hormonal",
        regimen: "Tamoxifen 20 mg daily ≥ 5 yrs",
        status: "in-progress",
        startDate: "2024-08-12",
        endDate: "2029-08-12",
      },
      {
        id: "ph-al-4",
        name: "Surveillance",
        type: "observation",
        regimen: "Mammography q6mo × 2 yrs, then annually · clinical exam q3mo",
        status: "in-progress",
        startDate: "2024-08-15",
      },
    ],
    agent: {
      now: { action: "Drafting 18-month surveillance summary" },
      needsYou: [],
      recent: [
        {
          id: "ev-al-1",
          action: "Auto-booked mammogram for 2026-05-08",
          at: "2026-04-20T10:00:00Z",
          ref: { kind: "fact", id: "f-al-mam", label: "Mammography schedule" },
        },
        {
          id: "ev-al-2",
          action: "Merged CA 15-3 result · 21 U/mL",
          at: "2026-04-04T08:45:00Z",
        },
        {
          id: "ev-al-3",
          action: "Refilled tamoxifen · 90-day supply",
          at: "2026-03-22T14:00:00Z",
        },
      ],
    },
  },
];

export function getPatient(id: string): Patient | undefined {
  return patients.find((p) => p.id === id);
}

export function patientsByStatus(status: Patient["status"]): Patient[] {
  return patients.filter((p) => p.status === status);
}
