import type { Fact, Patient, TreatmentOption, BoardCase } from "../types";

const factsMaria: Fact[] = [
  {
    id: "f-mk-name",
    key: "demographics.name",
    label: "Name",
    value: "Maria Kowalski",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "Intake form · 2026-02-08",
      excerpt: "Patient: Maria Kowalski, DOB 1971-09-14, female",
      at: "2026-02-08T09:12:00Z",
      author: "Reception",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1971-09-14",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "Intake form · 2026-02-08",
      at: "2026-02-08T09:12:00Z",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-204881",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: {
      kind: "report",
      id: "doc-mk-intake",
      label: "EHR registration",
      at: "2026-02-08T09:12:00Z",
    },
    updatedAt: "2026-02-08T09:12:00Z",
  },
  {
    id: "f-mk-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Invasive ductal carcinoma, left breast",
    confidence: 0.99,
    group: "diagnosis",
    specialty: "pathology",
    source: {
      kind: "pathology",
      id: "path-mk-001",
      label: "Path report · core biopsy 2026-02-12",
      excerpt:
        "Microscopic: invasive ductal carcinoma, Nottingham grade 2 (3+3+1=7). Tumor measures 2.3 cm in greatest dimension on the core.",
      author: "Dr. R. Patel, MD",
      at: "2026-02-13T14:30:00Z",
    },
    updatedAt: "2026-02-13T14:30:00Z",
  },
  {
    id: "f-mk-receptors",
    key: "diagnosis.receptors",
    label: "Receptor status",
    value: "ER+ (95%) · PR+ (60%) · HER2 3+ (IHC) confirmed by FISH",
    confidence: 0.98,
    group: "diagnosis",
    specialty: "pathology",
    source: {
      kind: "pathology",
      id: "path-mk-002",
      label: "IHC + FISH addendum · 2026-02-15",
      excerpt:
        "ER 95% strong, PR 60% moderate, HER2 IHC 3+; FISH HER2/CEP17 ratio 4.2 — amplified.",
      author: "Dr. R. Patel, MD",
      at: "2026-02-15T11:05:00Z",
    },
    updatedAt: "2026-02-15T11:05:00Z",
  },
  {
    id: "f-mk-stage",
    key: "staging.clinical",
    label: "Clinical stage",
    value: "cT2 cN1 cM0 — Stage IIB",
    confidence: 0.95,
    group: "staging",
    specialty: "radiology",
    source: {
      kind: "imaging",
      id: "img-mk-mri-001",
      label: "Breast MRI · 2026-02-19",
      excerpt:
        "2.4 cm enhancing mass at 2 o'clock left breast; one suspicious left axillary level I node (1.1 cm).",
      author: "Dr. K. Lee, Radiology",
      at: "2026-02-19T16:40:00Z",
    },
    updatedAt: "2026-02-19T16:40:00Z",
  },
  {
    id: "f-mk-tchp",
    key: "medication.neoadjuvant",
    label: "Neoadjuvant regimen",
    value: "TCHP — docetaxel + carboplatin + trastuzumab + pertuzumab, q3w × 6",
    confidence: 0.97,
    group: "medication",
    specialty: "med-onc",
    source: {
      kind: "note",
      id: "note-mk-tb-1",
      label: "Tumor board minutes · 2026-02-22",
      excerpt:
        "Consensus: HER2+ Stage IIB → neoadjuvant TCHP × 6 → surgery → adjuvant HP + endocrine therapy.",
      author: "Tumor board",
      at: "2026-02-22T10:00:00Z",
    },
    updatedAt: "2026-02-22T10:00:00Z",
  },
  {
    id: "f-mk-cycle",
    key: "medication.cycle",
    label: "Current cycle",
    value: "TCHP cycle 4 of 6 — last infusion 2026-04-15",
    confidence: 1,
    group: "medication",
    specialty: "nursing",
    source: {
      kind: "note",
      id: "note-mk-infusion-4",
      label: "Infusion note · 2026-04-15",
      author: "Onc nursing",
      at: "2026-04-15T13:00:00Z",
    },
    updatedAt: "2026-04-15T13:00:00Z",
  },
  {
    id: "f-mk-lvef",
    key: "lab.lvef",
    label: "LVEF (echo)",
    value: "62% — within normal limits",
    confidence: 0.99,
    group: "lab",
    specialty: "med-onc",
    source: {
      kind: "report",
      id: "echo-mk-002",
      label: "Echocardiogram · 2026-04-22",
      excerpt:
        "Normal LV size and systolic function. EF 62% by Simpson biplane. No regional wall abnormalities.",
      author: "Dr. A. Singh, Cardiology",
      at: "2026-04-22T09:30:00Z",
    },
    updatedAt: "2026-04-22T09:30:00Z",
  },
  {
    id: "f-mk-cbc",
    key: "lab.cbc",
    label: "ANC (latest)",
    value: "2.1 ×10⁹/L",
    confidence: 1,
    group: "lab",
    specialty: "med-onc",
    source: {
      kind: "lab",
      id: "lab-mk-cbc-3",
      label: "CBC · 2026-04-21",
      author: "Hematology lab",
      at: "2026-04-21T08:15:00Z",
    },
    updatedAt: "2026-04-21T08:15:00Z",
  },
  {
    id: "f-mk-hist1",
    key: "history.event.first-presentation",
    label: "First presentation",
    value: "Self-detected 2 cm lump, left breast — 2026-02-04",
    confidence: 0.95,
    group: "history",
    specialty: "patient",
    source: {
      kind: "note",
      id: "note-mk-pcp",
      label: "PCP referral letter",
      at: "2026-02-06T10:00:00Z",
    },
    updatedAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "f-mk-ngs",
    key: "genomics.panel",
    label: "NGS panel (FoundationOne CDx)",
    value: "PIK3CA p.H1047R · ERBB2 amp · TP53 wild-type · TMB 4 mut/Mb · MSS",
    confidence: 0.95,
    group: "genomics",
    specialty: "molecular",
    source: {
      kind: "genomics",
      id: "ngs-mk-001",
      label: "FoundationOne CDx report · 2026-02-26",
      excerpt:
        "Reportable: ERBB2 amplification (cn=14), PIK3CA c.3140A>G p.H1047R (VAF 32%). VUS: ARID1A. TMB 4. MSS.",
      author: "Foundation Medicine",
      at: "2026-02-26T12:00:00Z",
      specialty: "molecular",
    },
    updatedAt: "2026-02-26T12:00:00Z",
  },
  {
    id: "f-mk-oncokb",
    key: "genomics.oncokb",
    label: "OncoKB therapeutic level",
    value:
      "ERBB2 amp · Level 1 (trastuzumab + pertuzumab) · PIK3CA H1047R · Level 1 (alpelisib in HR+/HER2−)",
    confidence: 0.92,
    group: "genomics",
    specialty: "molecular",
    source: {
      kind: "genomics",
      id: "oncokb-mk-001",
      label: "OncoKB lookup · 2026-02-27",
      author: "OncoKB v4.20",
      at: "2026-02-27T08:30:00Z",
      specialty: "molecular",
    },
    updatedAt: "2026-02-27T08:30:00Z",
  },
  {
    id: "f-mk-surg-consult",
    key: "history.surg-consult",
    label: "Surgical consult",
    value:
      "Lumpectomy + SLNB feasible if good response to neoadjuvant; reassess at MRI mid-cycle 4",
    confidence: 0.85,
    group: "history",
    specialty: "surg-onc",
    source: {
      kind: "note",
      id: "note-mk-surg-1",
      label: "Surgical oncology note · 2026-02-21",
      excerpt:
        "After examination and review of MRI: candidate for breast-conserving surgery if neoadjuvant achieves >50% volumetric response. Plan SLNB at the time of surgery.",
      author: "Dr. S. Chen, Surgical Onc",
      at: "2026-02-21T10:30:00Z",
      specialty: "surg-onc",
    },
    updatedAt: "2026-02-21T10:30:00Z",
  },
  {
    id: "f-mk-rt-consult",
    key: "history.rt-consult",
    label: "Radiation oncology consult",
    value:
      "Whole-breast RT post-lumpectomy planned (40.05 Gy / 15 fx); boost to tumor bed if margins narrow",
    confidence: 0.85,
    group: "history",
    specialty: "rad-onc",
    source: {
      kind: "note",
      id: "note-mk-rt-1",
      label: "Rad-onc consult · 2026-02-23",
      author: "Dr. K. Lee, Rad-Onc",
      at: "2026-02-23T15:00:00Z",
      specialty: "rad-onc",
    },
    updatedAt: "2026-02-23T15:00:00Z",
  },
  {
    id: "f-mk-pharm",
    key: "medication.pharmacy-review",
    label: "Pharmacy review",
    value:
      "TCHP doses verified vs BSA 1.74; no QTc / renal flags; pre-meds dexa+ondansetron+aprepitant",
    confidence: 0.98,
    group: "medication",
    specialty: "pharmacy",
    source: {
      kind: "note",
      id: "note-mk-pharm-1",
      label: "Clinical pharmacy review · 2026-02-24",
      excerpt:
        "Docetaxel 75 mg/m² → 130 mg. Carboplatin AUC 6 (Calvert, GFR 88) → 540 mg. Trastuzumab 8 mg/kg loading, 6 mg/kg q3w. Pertuzumab 840 mg loading, 420 mg q3w. No interactions w/ home meds.",
      author: "PharmD A. Riesgo",
      at: "2026-02-24T16:00:00Z",
      specialty: "pharmacy",
    },
    updatedAt: "2026-02-24T16:00:00Z",
  },
];

const optionsMaria: TreatmentOption[] = [
  {
    id: "opt-mk-A",
    name: "Standard of care",
    shortLabel:
      "Neoadjuvant TCHP × 6 → lumpectomy + SLNB → adjuvant HP + endocrine",
    intent: "curative",
    phases: [
      {
        id: "ph-mk-A-1",
        name: "Neoadjuvant TCHP",
        type: "chemo",
        regimen: "Docetaxel · carboplatin · trastuzumab · pertuzumab, q3w × 6",
        status: "in-progress",
        startDate: "2026-02-25",
        endDate: "2026-06-10",
        cycles: { total: 6, completed: 4 },
      },
      {
        id: "ph-mk-A-2",
        name: "Lumpectomy + SLNB",
        type: "surgery",
        regimen: "Breast-conserving surgery + sentinel-node biopsy",
        status: "planned",
        startDate: "2026-07-08",
      },
      {
        id: "ph-mk-A-3",
        name: "Whole-breast RT",
        type: "radiation",
        regimen: "40.05 Gy in 15 fractions",
        status: "planned",
        startDate: "2026-08-19",
        endDate: "2026-09-09",
      },
      {
        id: "ph-mk-A-4",
        name: "Adjuvant HP",
        type: "targeted",
        regimen: "Trastuzumab + pertuzumab to complete 1 year HER2 blockade",
        status: "planned",
        startDate: "2026-09-23",
        endDate: "2027-02-25",
      },
      {
        id: "ph-mk-A-5",
        name: "Adjuvant endocrine",
        type: "hormonal",
        regimen: "Aromatase inhibitor ≥ 5 years",
        status: "planned",
        startDate: "2026-09-23",
      },
    ],
    rationale: [
      "HER2+ Stage IIB → matches NCCN BINV pathway for neoadjuvant systemic.",
      "ER+ → endocrine therapy after HER2 blockade.",
      "LVEF 62% → safe for trastuzumab + pertuzumab.",
      "ERBB2 amp confirmed (OncoKB Level 1) → HER2 blockade backbone.",
    ],
    rationaleFactIds: [
      "f-mk-receptors",
      "f-mk-stage",
      "f-mk-lvef",
      "f-mk-ngs",
      "f-mk-oncokb",
    ],
    outcomes: [
      { label: "pCR (breast + axilla)", value: "50–65%", citation: "NeoSphere 2012" },
      { label: "5-year iDFS", value: "~84%", citation: "APHINITY 2017" },
      { label: "5-year OS", value: "~94%", citation: "APHINITY 2017" },
    ],
    toxicities: [
      { category: "Cardiotoxicity", severity: "Monitor LVEF q3 mo · ~2% gr3+" },
      { category: "Neuropathy (docetaxel)", severity: "~30% gr2+" },
      { category: "Neutropenia", severity: "G-CSF support; ~10% febrile" },
      { category: "Alopecia", severity: "Expected, reversible" },
    ],
    evidence: ["NeoSphere 2012", "APHINITY 2017", "KATHERINE 2019", "NCCN BINV"],
    burden: "≈ 14 mo total · 18 infusions · 1 surgery · 15 RT fractions · 5+ yrs endocrine",
    rankings: [
      { specialist: "Dr. J. Müller", specialty: "med-onc", rank: 1, confidence: 0.95 },
      { specialist: "Dr. R. Patel", specialty: "pathology", rank: 1, confidence: 0.9 },
      { specialist: "Dr. S. Chen", specialty: "surg-onc", rank: 1, confidence: 0.85 },
      { specialist: "Dr. K. Lee", specialty: "rad-onc", rank: 1, confidence: 0.92 },
      { specialist: "PharmD A. Riesgo", specialty: "pharmacy", rank: 1, confidence: 0.88 },
    ],
    patientFacing: {
      name: "The standard treatment",
      summary:
        "Six rounds of chemotherapy with two HER2-targeted antibodies, then surgery to remove the tumor (keeping the breast), then radiation and a year of antibody-only treatment, plus a daily pill to block estrogen for at least five years.",
      livesLikeThis:
        "Most intense for the first 4–5 months. Hair loss is expected during chemo. Surgery is one day. Radiation is short daily visits for three weeks. The antibody year and the estrogen pill are well tolerated. Highest chance of cure.",
    },
  },
  {
    id: "opt-mk-B",
    name: "De-escalated",
    shortLabel: "Neoadjuvant TH × 4 → lumpectomy → adjuvant T-DM1 if residual disease",
    intent: "curative",
    phases: [
      {
        id: "ph-mk-B-1",
        name: "Neoadjuvant TH",
        type: "chemo",
        regimen: "Paclitaxel + trastuzumab, q1w × 12",
        status: "planned",
        startDate: "2026-02-25",
        endDate: "2026-05-19",
      },
      {
        id: "ph-mk-B-2",
        name: "Lumpectomy + SLNB",
        type: "surgery",
        status: "planned",
        startDate: "2026-06-16",
      },
      {
        id: "ph-mk-B-3",
        name: "Adjuvant (response-adapted)",
        type: "targeted",
        regimen: "T-DM1 × 14 if residual disease, else trastuzumab to 1 yr",
        status: "planned",
        startDate: "2026-08-04",
      },
      {
        id: "ph-mk-B-4",
        name: "Adjuvant endocrine",
        type: "hormonal",
        regimen: "Aromatase inhibitor ≥ 5 yrs",
        status: "planned",
        startDate: "2026-08-04",
      },
    ],
    rationale: [
      "Stage IIB but cT2 (smaller end) — APT/ATEMPT-style de-escalation candidate.",
      "Patient prioritizes lower toxicity, especially neuropathy.",
      "Response-adapted adjuvant via KATHERINE — switch to T-DM1 if non-pCR.",
    ],
    rationaleFactIds: ["f-mk-stage", "f-mk-receptors", "f-mk-oncokb"],
    outcomes: [
      { label: "pCR (breast + axilla)", value: "35–45%", citation: "ATEMPT 2021" },
      { label: "5-year iDFS", value: "~80%", citation: "KATHERINE 2019" },
      { label: "Severe neuropathy", value: "~10% (vs ~30% TCHP)", citation: "ATEMPT 2021" },
    ],
    toxicities: [
      { category: "Neuropathy", severity: "~10% gr2+" },
      { category: "Cardiotoxicity", severity: "Single-antibody risk lower" },
      { category: "Neutropenia", severity: "Mild" },
    ],
    evidence: ["ATEMPT 2021", "KATHERINE 2019", "NCCN BINV"],
    burden: "≈ 14 mo total · 12 weekly infusions · 1 surgery · 5+ yrs endocrine",
    rankings: [
      { specialist: "Dr. J. Müller", specialty: "med-onc", rank: 2, confidence: 0.7 },
      { specialist: "Dr. R. Patel", specialty: "pathology", rank: 2, confidence: 0.65 },
      { specialist: "Dr. S. Chen", specialty: "surg-onc", rank: 2, confidence: 0.7 },
      { specialist: "Dr. K. Lee", specialty: "rad-onc", rank: 2, confidence: 0.7 },
      { specialist: "PharmD A. Riesgo", specialty: "pharmacy", rank: 2, confidence: 0.75 },
    ],
    patientFacing: {
      name: "A gentler path",
      summary:
        "A milder weekly chemotherapy with one HER2 antibody for three months, then surgery, then up to a year of an antibody-only treatment that's adjusted to how well the chemo worked.",
      livesLikeThis:
        "Less intense weekly visits, much less likely to cause numb fingers/toes long-term. Slightly lower chance of complete tumor disappearance before surgery, but the year of antibody-only treatment afterwards catches up much of that gap.",
    },
  },
  {
    id: "opt-mk-C",
    name: "Trial — alpelisib add-on",
    shortLabel:
      "TCHP × 6 + alpelisib (PIK3CA H1047R) → surgery → adjuvant per response",
    intent: "trial",
    phases: [
      {
        id: "ph-mk-C-1",
        name: "TCHP + alpelisib (trial arm)",
        type: "chemo",
        regimen: "TCHP q3w × 6 + alpelisib 250 mg PO daily",
        status: "planned",
        startDate: "2026-02-25",
        endDate: "2026-06-10",
      },
      {
        id: "ph-mk-C-2",
        name: "Lumpectomy + SLNB",
        type: "surgery",
        status: "planned",
        startDate: "2026-07-08",
      },
      {
        id: "ph-mk-C-3",
        name: "Adjuvant (per response)",
        type: "targeted",
        regimen: "T-DM1 if non-pCR, else continue HP",
        status: "planned",
        startDate: "2026-08-04",
      },
    ],
    rationale: [
      "PIK3CA H1047R activating mutation present (OncoKB Level 1 in HR+/HER2−; investigational here).",
      "Open trial slot at NCT##### for HER2+ + PIK3CA-mut.",
      "Patient is interested in trial participation.",
    ],
    rationaleFactIds: ["f-mk-ngs", "f-mk-oncokb"],
    outcomes: [
      { label: "pCR (estimated)", value: "55–70%", citation: "NeoPHOEBE-style estimate" },
      { label: "Hyperglycemia gr3+", value: "~10%", citation: "SOLAR-1 2019" },
    ],
    toxicities: [
      { category: "Hyperglycemia", severity: "Common — SMBG required" },
      { category: "Rash", severity: "~10% gr2+" },
      { category: "Diarrhea", severity: "Common" },
    ],
    evidence: ["SOLAR-1 2019", "trial protocol NCT-PLACEHOLDER"],
    burden:
      "Same as Standard of care + daily oral pill + extra labs/visits for trial monitoring",
    rankings: [
      { specialist: "Dr. J. Müller", specialty: "med-onc", rank: 3, confidence: 0.55 },
      { specialist: "Dr. R. Patel", specialty: "pathology", rank: 2, confidence: 0.7 },
      { specialist: "Dr. S. Chen", specialty: "surg-onc", rank: 3, confidence: 0.5 },
      { specialist: "Dr. K. Lee", specialty: "rad-onc", rank: 3, confidence: 0.5 },
      { specialist: "PharmD A. Riesgo", specialty: "pharmacy", rank: 3, confidence: 0.6 },
    ],
    patientFacing: {
      name: "A clinical trial",
      summary:
        "The standard treatment plus an additional daily pill that targets a specific change in your tumor (PIK3CA), to see if it improves the chance of complete tumor disappearance.",
      livesLikeThis:
        "Same as the standard path, with extra blood-sugar monitoring and more frequent check-ins. Side effects we know about: high blood sugar, rash, diarrhea.",
    },
  },
];

const boardCaseMaria: BoardCase = {
  id: "case-mk-tx-decision",
  patientId: "maria-k",
  question:
    "HER2+ Stage IIB · ERBB2 amp · PIK3CA H1047R — neoadjuvant strategy and adjuvant sequencing.",
  openedAt: "2026-04-22T17:30:00Z",
  attendees: [
    { name: "Dr. J. Müller", role: "Med-Onc", tone: "violet" },
    { name: "Dr. R. Patel", role: "Pathology", tone: "rose" },
    { name: "Dr. S. Chen", role: "Surgical Onc", tone: "emerald" },
    { name: "Dr. K. Lee", role: "Rad-Onc + Radiology", tone: "amber" },
    { name: "PharmD A. Riesgo", role: "Pharmacy", tone: "sky" },
  ],
  status: "draft",
  decidedOptionId: null,
};

const factsThomas: Fact[] = [
  {
    id: "f-tb-name",
    key: "demographics.name",
    label: "Name",
    value: "Thomas Berger",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-tb-intake", label: "Intake form · 2026-03-01", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1958-06-21",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-tb-intake", label: "Intake form", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-198342",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-tb-intake", label: "EHR registration", at: "2026-03-01T08:30:00Z" },
    updatedAt: "2026-03-01T08:30:00Z",
  },
  {
    id: "f-tb-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Adenocarcinoma of the rectum, mid-rectum (8 cm from anal verge)",
    confidence: 0.99,
    group: "diagnosis",
    specialty: "pathology",
    source: {
      kind: "pathology",
      id: "path-tb-001",
      label: "Colonoscopy biopsy report · 2026-03-04",
      excerpt:
        "Mid-rectum 3.5 cm ulcerated mass at 8 cm from anal verge. Biopsy: moderately differentiated adenocarcinoma.",
      author: "Dr. M. Schwarz, GI Path",
      at: "2026-03-04T15:20:00Z",
    },
    updatedAt: "2026-03-04T15:20:00Z",
  },
  {
    id: "f-tb-stage",
    key: "staging.clinical",
    label: "Clinical stage",
    value: "cT3 cN1 cM0 — Stage IIIB",
    confidence: 0.7,
    group: "staging",
    specialty: "radiology",
    source: {
      kind: "imaging",
      id: "img-tb-mri-001",
      label: "Pelvic MRI · 2026-03-08",
      excerpt:
        "Mid-rectal mass with extramural extension into mesorectal fat (cT3, EMVI−). One suspicious mesorectal node 9 mm.",
      author: "Dr. K. Lee, Radiology",
      at: "2026-03-08T11:10:00Z",
    },
    updatedAt: "2026-03-08T11:10:00Z",
  },
  {
    id: "f-tb-cea",
    key: "lab.cea",
    label: "CEA",
    value: "8.4 ng/mL (elevated)",
    confidence: 1,
    group: "lab",
    specialty: "med-onc",
    source: { kind: "lab", id: "lab-tb-cea-1", label: "CEA · 2026-03-05", at: "2026-03-05T07:50:00Z" },
    updatedAt: "2026-03-05T07:50:00Z",
  },
  {
    id: "f-tb-folfox",
    key: "medication.induction",
    label: "Induction chemotherapy",
    value: "FOLFOX × 4 cycles (TNT — induction phase)",
    confidence: 0.96,
    group: "medication",
    specialty: "med-onc",
    source: {
      kind: "note",
      id: "note-tb-tb-1",
      label: "Tumor board minutes · 2026-03-12",
      excerpt:
        "Plan: total neoadjuvant therapy — induction FOLFOX × 4 → long-course CRT → TME → adjuvant if indicated.",
      author: "Tumor board",
      at: "2026-03-12T09:00:00Z",
    },
    updatedAt: "2026-03-12T09:00:00Z",
  },
  {
    id: "f-tb-cycle",
    key: "medication.cycle",
    label: "Current cycle",
    value: "FOLFOX cycle 4 of 4 — completed 2026-04-18",
    confidence: 1,
    group: "medication",
    specialty: "nursing",
    source: {
      kind: "note",
      id: "note-tb-infusion-4",
      label: "Infusion note · 2026-04-18",
      at: "2026-04-18T14:20:00Z",
    },
    updatedAt: "2026-04-18T14:20:00Z",
  },
  {
    id: "f-tb-mri-restage",
    key: "imaging.restage",
    label: "Restaging MRI",
    value: "Pelvic MRI · 2026-04-22 (incoming PR)",
    confidence: 0.85,
    group: "imaging",
    specialty: "radiology",
    source: {
      kind: "imaging",
      id: "img-tb-mri-002",
      label: "Pelvic MRI · 2026-04-22",
      excerpt:
        "Compared to 2026-03-08: tumor enhancement reduced ~30% but anterior extension now contacts visceral peritoneum (suggestive of cT4a). One persistent 7 mm mesorectal node.",
      author: "Dr. K. Lee, Radiology",
      at: "2026-04-22T16:00:00Z",
    },
    updatedAt: "2026-04-22T16:00:00Z",
  },
];

const factsAnna: Fact[] = [
  {
    id: "f-al-name",
    key: "demographics.name",
    label: "Name",
    value: "Anna Lindqvist",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-al-intake", label: "Intake form · 2024-02-19", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-dob",
    key: "demographics.dob",
    label: "Date of birth",
    value: "1977-11-02",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-al-intake", label: "Intake form", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-mrn",
    key: "demographics.mrn",
    label: "MRN",
    value: "MRN-176104",
    confidence: 1,
    group: "demographics",
    specialty: "nursing",
    source: { kind: "report", id: "doc-al-intake", label: "EHR registration", at: "2024-02-19T10:00:00Z" },
    updatedAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "f-al-dx",
    key: "diagnosis.primary",
    label: "Primary diagnosis",
    value: "Invasive lobular carcinoma, right breast",
    confidence: 0.98,
    group: "diagnosis",
    specialty: "pathology",
    source: {
      kind: "pathology",
      id: "path-al-001",
      label: "Lumpectomy specimen · 2024-04-09",
      excerpt:
        "Invasive lobular carcinoma, 1.4 cm, grade 2. Margins clear. 0/2 sentinel nodes positive.",
      author: "Dr. R. Patel, MD",
      at: "2024-04-12T11:00:00Z",
    },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-stage",
    key: "staging.pathologic",
    label: "Pathologic stage",
    value: "pT1c pN0 — Stage IA",
    confidence: 0.99,
    group: "staging",
    specialty: "pathology",
    source: {
      kind: "pathology",
      id: "path-al-001",
      label: "Lumpectomy specimen · 2024-04-09",
      at: "2024-04-12T11:00:00Z",
    },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-receptors",
    key: "diagnosis.receptors",
    label: "Receptor status",
    value: "ER+ (98%) · PR+ (75%) · HER2 0 (negative)",
    confidence: 0.98,
    group: "diagnosis",
    specialty: "pathology",
    source: { kind: "pathology", id: "path-al-001", label: "IHC panel", at: "2024-04-12T11:00:00Z" },
    updatedAt: "2024-04-12T11:00:00Z",
  },
  {
    id: "f-al-tam",
    key: "medication.endocrine",
    label: "Endocrine therapy",
    value: "Tamoxifen 20 mg daily — start 2024-08-12, planned ≥ 5 yrs",
    confidence: 1,
    group: "medication",
    specialty: "med-onc",
    source: {
      kind: "note",
      id: "note-al-tam",
      label: "Med-onc note · 2024-08-05",
      author: "Dr. J. Müller, Med-Onc",
      at: "2024-08-05T13:00:00Z",
    },
    updatedAt: "2024-08-05T13:00:00Z",
  },
  {
    id: "f-al-mam",
    key: "imaging.surveillance",
    label: "Last mammogram",
    value: "Bilateral mammogram · 2025-10-14 — BI-RADS 2 (benign)",
    confidence: 0.99,
    group: "imaging",
    specialty: "radiology",
    source: {
      kind: "imaging",
      id: "img-al-mam-3",
      label: "Mammogram · 2025-10-14",
      author: "Dr. K. Lee, Radiology",
      at: "2025-10-14T09:00:00Z",
    },
    updatedAt: "2025-10-14T09:00:00Z",
  },
  {
    id: "f-al-ca153",
    key: "lab.ca153",
    label: "CA 15-3",
    value: "21 U/mL (within normal)",
    confidence: 1,
    group: "lab",
    specialty: "med-onc",
    source: { kind: "lab", id: "lab-al-ca153-2", label: "CA 15-3 · 2026-04-04", at: "2026-04-04T08:00:00Z" },
    updatedAt: "2026-04-04T08:00:00Z",
  },
];

export const patients: Patient[] = [
  {
    id: "maria-k",
    name: "Maria Kowalski",
    initials: "MK",
    dob: "1971-09-14",
    age: 54,
    sex: "F",
    mrn: "MRN-204881",
    status: "active",
    cancerType: "breast-her2",
    cancerLabel: "HER2+ breast cancer · Stage IIB",
    diagnosis: "Invasive ductal carcinoma, ER+/PR+/HER2 3+",
    staging: "cT2 cN1 cM0",
    primaryOncologist: "Dr. J. Müller, Med-Onc",
    caseOpenedAt: "2026-02-08",
    avatarTone: "rose",
    vaultAvatars: [
      { initials: "JM", tone: "violet" },
      { initials: "RP", tone: "rose" },
      { initials: "AS", tone: "emerald" },
      { initials: "KL", tone: "amber" },
    ],
    facts: factsMaria,
    options: optionsMaria,
    chosenOptionId: null,
    boardCase: boardCaseMaria,
    plan: [
      {
        id: "ph-mk-1",
        name: "Neoadjuvant TCHP",
        type: "chemo",
        regimen: "Docetaxel · carboplatin · trastuzumab · pertuzumab",
        status: "in-progress",
        startDate: "2026-02-25",
        endDate: "2026-06-10",
        cycles: { total: 6, completed: 4 },
        rationale: "HER2+ Stage IIB → standard of care neoadjuvant TCHP × 6 (NCCN BINV-J).",
      },
      {
        id: "ph-mk-2",
        name: "Surgery",
        type: "surgery",
        regimen: "Lumpectomy + sentinel node biopsy (axillary dissection if positive)",
        status: "planned",
        startDate: "2026-07-08",
        rationale: "Clinical stage IIB with planned breast-conserving therapy if good response.",
      },
      {
        id: "ph-mk-3",
        name: "Adjuvant HP",
        type: "targeted",
        regimen: "Trastuzumab + pertuzumab to complete 1 year HER2-targeted therapy",
        status: "planned",
        startDate: "2026-08-12",
        endDate: "2027-02-25",
        rationale: "1-year HER2 blockade reduces recurrence risk.",
      },
      {
        id: "ph-mk-4",
        name: "Adjuvant endocrine",
        type: "hormonal",
        regimen: "Aromatase inhibitor (post-menopausal) for ≥ 5 years",
        status: "planned",
        startDate: "2026-08-12",
        rationale: "ER/PR positive disease — endocrine therapy for ≥ 5 years.",
      },
    ],
    agent: {
      now: {
        action: "Reviewing 2026-04-22 echocardiogram for trastuzumab cardiac monitoring",
      },
      needsYou: [
        {
          id: "q-mk-1",
          question: "Confirm continued TCHP after Cycle 4 — ANC 2.1, no DLT",
          detail:
            "Neutrophils marginal but acceptable per protocol. Endorse continuation of cycle 5 on schedule?",
          ref: { kind: "fact", id: "f-mk-cbc", label: "ANC 2.1 ×10⁹/L" },
          options: ["Continue on schedule", "Delay 1 week", "Reduce dose"],
        },
      ],
      recent: [
        {
          id: "ev-mk-1",
          action: "Merged echocardiogram report · LVEF 62%",
          at: "2026-04-22T11:02:00Z",
          ref: { kind: "pr", id: "pr-mk-2", label: "Echo 2026-04-22" },
        },
        {
          id: "ev-mk-2",
          action: "Linked CBC 2026-04-21 to cycle 4 progress",
          at: "2026-04-21T08:30:00Z",
        },
        {
          id: "ev-mk-3",
          action: "Auto-scheduled mid-treatment MRI for 2026-05-13",
          at: "2026-04-19T16:14:00Z",
        },
      ],
    },
  },
  {
    id: "thomas-b",
    name: "Thomas Berger",
    initials: "TB",
    dob: "1958-06-21",
    age: 67,
    sex: "M",
    mrn: "MRN-198342",
    status: "active",
    cancerType: "rectal",
    cancerLabel: "Rectal adenocarcinoma · TNT in progress",
    diagnosis: "Adenocarcinoma of the rectum, mid-rectum",
    staging: "cT3 cN1 cM0 (provisional → cT4a pending)",
    primaryOncologist: "Dr. C. Romano, Med-Onc",
    caseOpenedAt: "2026-03-01",
    avatarTone: "violet",
    vaultAvatars: [
      { initials: "CR", tone: "violet" },
      { initials: "MS", tone: "rose" },
      { initials: "KL", tone: "amber" },
      { initials: "FP", tone: "sky" },
    ],
    facts: factsThomas,
    plan: [
      {
        id: "ph-tb-1",
        name: "Induction FOLFOX",
        type: "chemo",
        regimen: "Oxaliplatin + 5-FU + leucovorin, q2w × 4",
        status: "done",
        startDate: "2026-03-15",
        endDate: "2026-04-18",
        cycles: { total: 4, completed: 4 },
        rationale: "Total neoadjuvant therapy — induction phase.",
      },
      {
        id: "ph-tb-2",
        name: "Long-course CRT",
        type: "radiation",
        regimen: "50.4 Gy in 28 fractions + concurrent capecitabine",
        status: "planned",
        startDate: "2026-05-06",
        endDate: "2026-06-17",
        rationale: "TNT consolidation — long-course chemoradiation.",
      },
      {
        id: "ph-tb-3",
        name: "TME surgery",
        type: "surgery",
        regimen: "Total mesorectal excision (low anterior resection)",
        status: "planned",
        startDate: "2026-08-05",
        rationale:
          "Standard surgical approach following TNT, 6–8 weeks after CRT completion.",
      },
      {
        id: "ph-tb-4",
        name: "Adjuvant (if indicated)",
        type: "chemo",
        regimen: "Adjuvant FOLFOX or capecitabine if path response < grade 3",
        status: "planned",
        startDate: "2026-09-23",
        rationale: "Risk-adapted adjuvant per pathologic response.",
      },
    ],
    agent: {
      now: {
        action: "Reconciling restaging MRI vs. baseline staging",
        ref: { kind: "pr", id: "pr-tb-1", label: "PR #3 — MRI 2026-04-22" },
      },
      needsYou: [
        {
          id: "q-tb-1",
          question: "MRI 2026-04-22 suggests cT4a — change of staging vs. cT3",
          detail:
            "Anterior extension contacts visceral peritoneum. This conflicts with the prior cT3 from 2026-03-08. Possible explanations: progression on induction, MRI re-read, or interval inflammation. Plan implications: TNT may need to escalate, consider surgical re-staging.",
          ref: { kind: "pr", id: "pr-tb-1", label: "PR #3 — MRI 2026-04-22" },
          options: [
            "Accept cT4a — escalate plan",
            "Request second MRI read",
            "Discuss at tumor board",
          ],
        },
      ],
      recent: [
        {
          id: "ev-tb-1",
          action: "Flagged staging conflict on MRI 2026-04-22",
          at: "2026-04-22T17:14:00Z",
          ref: { kind: "pr", id: "pr-tb-1", label: "PR #3" },
        },
        {
          id: "ev-tb-2",
          action: "Merged FOLFOX cycle 4 infusion note",
          at: "2026-04-18T15:00:00Z",
        },
        {
          id: "ev-tb-3",
          action: "Auto-booked tumor board slot · 2026-04-26 09:00",
          at: "2026-04-22T17:30:00Z",
          ref: { kind: "meeting", id: "mtg-tb-1", label: "Tumor board · 2026-04-26" },
        },
      ],
    },
  },
  {
    id: "anna-l",
    name: "Anna Lindqvist",
    initials: "AL",
    dob: "1977-11-02",
    age: 48,
    sex: "F",
    mrn: "MRN-176104",
    status: "surveillance",
    cancerType: "breast-er",
    cancerLabel: "ER+ breast cancer · Surveillance · 23 mo",
    diagnosis: "Invasive lobular carcinoma, ER+/PR+/HER2−",
    staging: "pT1c pN0 — Stage IA",
    primaryOncologist: "Dr. J. Müller, Med-Onc",
    caseOpenedAt: "2024-02-19",
    avatarTone: "emerald",
    vaultAvatars: [
      { initials: "JM", tone: "violet" },
      { initials: "RP", tone: "rose" },
      { initials: "KL", tone: "amber" },
    ],
    facts: factsAnna,
    plan: [
      {
        id: "ph-al-1",
        name: "Lumpectomy + SLNB",
        type: "surgery",
        status: "done",
        startDate: "2024-04-09",
        endDate: "2024-04-09",
        rationale: "Breast-conserving surgery, sentinel node biopsy negative.",
      },
      {
        id: "ph-al-2",
        name: "Adjuvant radiation",
        type: "radiation",
        regimen: "Whole-breast 40.05 Gy in 15 fractions",
        status: "done",
        startDate: "2024-06-03",
        endDate: "2024-07-12",
      },
      {
        id: "ph-al-3",
        name: "Endocrine therapy",
        type: "hormonal",
        regimen: "Tamoxifen 20 mg daily ≥ 5 yrs",
        status: "in-progress",
        startDate: "2024-08-12",
        endDate: "2029-08-12",
      },
      {
        id: "ph-al-4",
        name: "Surveillance",
        type: "observation",
        regimen: "Mammography q6mo × 2 yrs, then annually · clinical exam q3mo",
        status: "in-progress",
        startDate: "2024-08-15",
      },
    ],
    agent: {
      now: { action: "Drafting 18-month surveillance summary" },
      needsYou: [],
      recent: [
        {
          id: "ev-al-1",
          action: "Auto-booked mammogram for 2026-05-08",
          at: "2026-04-20T10:00:00Z",
          ref: { kind: "fact", id: "f-al-mam", label: "Mammography schedule" },
        },
        {
          id: "ev-al-2",
          action: "Merged CA 15-3 result · 21 U/mL",
          at: "2026-04-04T08:45:00Z",
        },
        {
          id: "ev-al-3",
          action: "Refilled tamoxifen · 90-day supply",
          at: "2026-03-22T14:00:00Z",
        },
      ],
    },
  },
];

export function getPatient(id: string): Patient | undefined {
  return patients.find((p) => p.id === id);
}

export function patientsByStatus(status: Patient["status"]): Patient[] {
  return patients.filter((p) => p.status === status);
}
